default: &default
  adapter: postgresql
  host: localhost
  user: postgres
  password: postgres
  encoding: utf-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: life_planner_development

test:
  <<: *default
  database: life_planner_test

production:
  primary: &primary_production
    <<: *default
    database: life_planner_production
    username: life_planner
    password: <%= ENV["LIFE_PLANNER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: life_planner_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: life_planner_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: life_planner_production_cable
    migrations_paths: db/cable_migrate
